name: grace_env
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=3.2.0
  - idna=3.4
  - joblib=1.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.23
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - ncurses=6.4
  - numpy=1.25.1
  - openssl=3.1.1
  - packaging=23.1
  - pip=23.1.2
  - platformdirs=3.8.1
  - pooch=1.7.0
  - pysocks=1.7.1
  - python=3.11.4
  - python_abi=3.11
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - typing-extensions
  - typing_extensions
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.1
      - click==8.1.6
      - contourpy==1.1.0
      - cvxopt==1.3.1
      - cycler==0.11.0
      - filelock==3.12.2
      - fonttools==4.40.0
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - imageio==2.31.1
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - magicgui==0.7.2
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - mrcfile==1.4.3
      - networkx==3.1
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - pandas==2.0.3
      - pillow==10.0.0
      - pluggy==1.2.0
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.0.9
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qtpy==2.3.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.21.0
      - seaborn==0.12.2
      - six==1.16.0
      - starfile==0.4.12
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tifffile==2023.7.10
      - torch==2.0.1
      - torch-geometric==2.3.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.6
