# Paths to data:

train_image_dir: /path/to/your/train/images
train_grace_dir: /path/to/your/train/annotations
valid_image_dir: /path/to/your/valid/images
valid_grace_dir: /path/to/your/valid/annotations
infer_image_dir: /path/to/your/infer/images
infer_grace_dir: /path/to/your/infer/annotations
log_dir: /path/to/your/classifier/runs

# Data image file type & graph annotations:
filetype: mrc
keep_node_unknown_labels: False     # relabels UNKNOWN nodes to TRUE_NEGATIVE
keep_edge_unknown_labels: False     # relabels UNKNOWN edges to TRUE_NEGATIVE

# Feature extractor path & patch normalization:
extractor_fn: /path/to/your/extractor/resnet152.pt
patch_size:           # input dimensionality: 2D patch shape
  - 224
  - 224
feature_dim: 2048     # output dimensionality: 1D feature vector
normalise:            # [0-1] image patch standardisation
  - False             # before augmentations
  - False             # after augmentations

# Patch & graph augmentations specs:
img_graph_augs: []          # see 'grace.utils/augment_graph.py' for full option list
img_graph_aug_params: []
patch_augs: []              # see 'grace.utils/augment_image.py' for full option list
patch_aug_params: []
keep_patch_fraction: 1.0    # original patch image ration to include in training

# Subgraph dataset builder:
batch_size: 512
num_hops: 1
connection: spiderweb

# Classifier architecture setup
classifier_type: GAT
num_attention_heads: 1
num_node_classes: 2
num_edge_classes: 2
hidden_graph_channels:
  - 512
#  - 64
hidden_dense_channels:
  - 128
#  - 64

# Training run hyperparameters
epochs: 500
dropout: 0.0
learning_rate: 0.05
weight_decay: 0.0

# Learning rate scheduler:
scheduler_type: expo
scheduler_step: 5
scheduler_gamma: 0.99

# Validation monitoring:
tensorboard_update_frequency: 1  # stores loss / metrics output every X epochs
valid_graph_ploter_frequency: 20
animate_valid_progress: False
visualise_tsne_manifold: False

# Performance metrics evaluation:
metrics_classifier:
  - accuracy
  - f1_score
  - confusion_matrix
metrics_objects:
  - exact
  - approx
